# Generated by Django 5.1.6 on 2025-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
