# Generated by Django 5.1.6 on 2025-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_section', '0002_alter_leads_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='care_of',
            field=models.CharField(blank=True, default='Nil', max_length=100, null=True),
        ),
    ]
