# Generated by Django 5.1.6 on 2025-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingDataPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_pdf', models.FileField(blank=True, null=True, upload_to='match_pdfs/')),
            ],
        ),
    ]
