# Generated by Django 5.1.6 on 2025-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank_section', '0003_alter_databank_area_in_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
